/**
 * Deterministic re-base of generated spec HTML files onto the current
 * base.html template.
 *
 * A spec HTML file is chrome (styles, component script, header, reader
 * script — machine-owned) plus content (the #relic-body sections and the
 * three embedded markdown source blocks — LLM-authored). Re-basing swaps
 * the chrome for the current template's version while preserving content,
 * so template fixes reach files generated by older Relic versions without
 * an LLM in the loop.
 */

export interface SpecHtmlParts {
  specId: string;
  title: string;
  /** The full `<div id="relic-body">…</div>` block. */
  bodyBlock: string;
  srcSpec: string;
  srcPlan: string;
  srcTasks: string;
}

const CONTENT_REGION = /<!-- relic:content:start -->([\s\S]*?)<!-- relic:content:end -->/;
/** Legacy files (no sentinels): greedy to the last </div> that directly precedes a <script> or </body>. */
const LEGACY_BODY = /(<div id="relic-body">[\s\S]*<\/div>)\s*(?=<script|<\/body>)/;

function srcBlockRe(id: string): RegExp {
  return new RegExp(
    `(<script type="text/plain" id="${id}">)([\\s\\S]*?)(</script>)`
  );
}

export function extractSpecHtmlParts(html: string): SpecHtmlParts | null {
  let specId = html.match(/<span class="h-id">([^<]*)<\/span>/)?.[1]?.trim() ?? "";
  let title = html.match(/<span class="h-title">([^<]*)<\/span>/)?.[1]?.trim() ?? "";
  if (!specId || !title) {
    const tm = html.match(/<title>([^<]*?)\s+—\s+([^<]*)<\/title>/);
    if (tm) {
      specId = specId || (tm[1] ?? "").trim();
      title = title || (tm[2] ?? "").trim();
    }
  }
  if (!specId) return null;

  let bodyBlock: string | null = null;
  const sentinel = html.match(CONTENT_REGION);
  if (sentinel) {
    bodyBlock = (sentinel[1] ?? "").trim();
  } else {
    const legacy = html.match(LEGACY_BODY);
    if (legacy) bodyBlock = legacy[1] ?? null;
  }
  if (!bodyBlock || !bodyBlock.includes('<div id="relic-body">')) return null;

  const src = (id: string) => html.match(srcBlockRe(id))?.[2] ?? "";

  return {
    specId,
    title: title || specId,
    bodyBlock,
    srcSpec: src("relic-src-spec"),
    srcPlan: src("relic-src-plan"),
    srcTasks: src("relic-src-tasks"),
  };
}

/**
 * A literal `</script` inside an embedded source block would terminate the
 * block and dump the rest of the markdown into the page as live HTML. The
 * writer escapes it with a backslash; the in-page reader converts it back.
 */
export function escapeMdForScriptBlock(md: string): string {
  return md.replace(/<\/(script)/gi, "<\\/$1");
}

/**
 * Embed the current markdown file contents into the three reader source
 * blocks. Files are the source of truth — whatever the blocks held before
 * is replaced.
 */
export function embedMarkdownSources(
  html: string,
  sources: { spec: string; plan: string; tasks: string }
): string {
  let out = html;
  for (const [id, content] of [
    ["relic-src-spec", sources.spec],
    ["relic-src-plan", sources.plan],
    ["relic-src-tasks", sources.tasks],
  ] as const) {
    const escaped = escapeMdForScriptBlock(content);
    out = out.replace(srcBlockRe(id), (_m, open, _old, close) => `${open}${escaped}${close}`);
  }
  return out;
}

/**
 * Rebuild a spec HTML file from the current base template, carrying over the
 * authored content of `oldHtml`. Returns null when the old file's structure
 * is unrecognisable (no spec id or no #relic-body) — such files are skipped,
 * never overwritten.
 */
export function rebaseSpecHtml(
  oldHtml: string,
  baseTemplate: string,
  date: string
): string | null {
  const parts = extractSpecHtmlParts(oldHtml);
  if (!parts) return null;

  let out = baseTemplate
    .replace(/\{\{SPEC_ID\}\}/g, parts.specId)
    .replace(/\{\{TITLE\}\}/g, parts.title)
    .replace(/\{\{DATE\}\}/g, date);

  if (!CONTENT_REGION.test(out)) return null; // template must carry sentinels

  // Function replacers throughout: content may contain `$` sequences that
  // string replacements would interpret.
  out = out.replace(
    CONTENT_REGION,
    () => `<!-- relic:content:start -->\n${parts.bodyBlock}\n<!-- relic:content:end -->`
  );

  for (const [id, content] of [
    ["relic-src-spec", parts.srcSpec],
    ["relic-src-plan", parts.srcPlan],
    ["relic-src-tasks", parts.srcTasks],
  ] as const) {
    out = out.replace(srcBlockRe(id), (_m, open, _old, close) => `${open}${content}${close}`);
  }

  return out;
}
