#!/usr/bin/env bun
/**
 * Builds the viewer (vite build) and embeds dist/ into
 * packages/cli-node/src/generated/viewer-assets.ts so `relic serve` can ship the
 * app from a single self-contained artifact (both distribution channels).
 *
 * Assets are stored base64-encoded (safe for any content type).
 *
 *   bun run scripts/embed-viewer.ts             # build + embed
 *   bun run scripts/embed-viewer.ts --no-build  # embed existing dist/
 */

import { spawnSync } from "child_process";
import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync, existsSync } from "fs";
import { join, relative, extname } from "path";

const ROOT = join(import.meta.dir, "..");
const VIEWER_DIR = join(ROOT, "packages", "viewer");
const DIST = join(VIEWER_DIR, "dist");
const OUT_FILE = join(ROOT, "packages/cli-node/src/generated/viewer-assets.ts");

const TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".map": "application/json",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
};

if (!process.argv.includes("--no-build")) {
  const res = spawnSync("bun", ["run", "build"], { cwd: VIEWER_DIR, stdio: "inherit" });
  if (res.status !== 0) {
    console.error("embed-viewer: vite build failed");
    process.exit(1);
  }
}

if (!existsSync(DIST)) {
  console.error(`embed-viewer: ${DIST} not found — run vite build first`);
  process.exit(1);
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const entries: string[] = [];
for (const file of walk(DIST).sort()) {
  const key = relative(DIST, file).replace(/\\/g, "/");
  const type = TYPES[extname(file)] ?? "application/octet-stream";
  const b64 = readFileSync(file).toString("base64");
  entries.push(`  ${JSON.stringify(key)}: { type: ${JSON.stringify(type)}, b64: ${JSON.stringify(b64)} }`);
}

const output = `// Auto-generated by scripts/embed-viewer.ts — do not edit manually.
// Source: packages/viewer/ (vite build output, base64-encoded).
export interface ViewerAsset { type: string; b64: string; }
export const VIEWER_ASSETS: Record<string, ViewerAsset> = {
${entries.join(",\n")},
};
`;

mkdirSync(join(ROOT, "packages/cli-node/src/generated"), { recursive: true });
writeFileSync(OUT_FILE, output, "utf8");
console.log(`Embedded ${entries.length} viewer assets → packages/cli-node/src/generated/viewer-assets.ts`);
