#!/usr/bin/env bun
/**
 * Embeds the canonical Relic skill into the engine package so every
 * distribution artifact can install it without access to the source checkout.
 *
 *   bun run scripts/embed-skill.ts          # generate
 *   bun run scripts/embed-skill.ts --check  # assert freshness
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SKILL_ROOT = join(ROOT, "skills", "relic");
const OUT_FILE = join(
  ROOT,
  "packages",
  "engines",
  "src",
  "generated",
  "relic-skill.ts",
);
const CHECK = process.argv.includes("--check");

function walk(directory: string): string[] {
  const result: string[] = [];
  for (const entry of readdirSync(directory).sort()) {
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) {
      result.push(...walk(path));
    } else {
      result.push(path);
    }
  }
  return result;
}

const entries = walk(SKILL_ROOT).map((path) => {
  const key = relative(SKILL_ROOT, path).replaceAll("\\", "/");
  const content = readFileSync(path, "utf8");
  return `  ${JSON.stringify(key)}: ${JSON.stringify(content)}`;
});

const output = `// Auto-generated by scripts/embed-skill.ts — do not edit manually.
// Source of truth: skills/relic/
export const RELIC_SKILL_FILES: Readonly<Record<string, string>> = {
${entries.join(",\n")},
};
`;

if (CHECK) {
  const current = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, "utf8") : "";
  if (current !== output) {
    console.error(
      "embed-skill --check: generated skill is stale — run: bun run build:skill",
    );
    process.exit(1);
  }
  console.log(`Relic skill embedding is current (${entries.length} files)`);
  process.exit(0);
}

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, output, "utf8");
console.log(
  `Embedded ${entries.length} Relic skill files → packages/engines/src/generated/relic-skill.ts`,
);
